name: github-profilemd-Generater
description: Generate profile cards and commit to default branch
author: kwangsing3

inputs:
  USERNAME:
    required: true
    description: 'GitHub username'
    default: ${{ github.repository_owner }}
  GITHUB_REPO_NAME:
    required: true
    description: 'repo name'
    default: ${{ github.event.repository.name }}
runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: 'activity'
  color: 'orange'