import { loadConfig } from './utils/config.js';
import uti_fs from './utils/fswr.js';
import uti_cli from './utils/cli.js';
import Logger from './utils/logger.js';

import generateLangComposCard from './svgcards/repo-language-cards.js';
import generateTagsStatCard from './svgcards/stat-card.js';
import generateOverviewCard from './svgcards/overview-card.js';

const CARDS = ['overview', 'langcompos', 'tagsstat'];

/* Build the embeddable README snippet listing every generated card. */
function buildReadme(config) {
    let content = `<!-- Generated by github-profilemd-Generater. Embed any of the cards below. -->\n\n`;
    for (const key of config.themes) {
        content += `### ${key}\n\n`;
        for (const card of CARDS) {
            content += `![](./github-profilemd-generater/${key}/${card}.svg)\n`;
        }
        content += `\n`;
    }
    return content;
}

async function main() {
    const config = loadConfig();

    if (!config.token) {
        Logger.setFailed(
            'GITHUB_TOKEN was empty. Pass it via `env: GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}`.'
        );
        process.exit(1);
    }
    if (!config.username) {
        Logger.setFailed('USERNAME was empty; check the workflow inputs.');
        process.exit(1);
    }

    Logger.info(
        `Generating cards for "${config.username}" ` +
            `(themes: ${config.themes.length}, topN: ${config.topN})...`
    );

    const generators = [
        ['overview', generateOverviewCard],
        ['language composition', generateLangComposCard],
        ['tags stat', generateTagsStatCard],
    ];

    let failures = 0;
    for (const [label, fn] of generators) {
        try {
            await fn(config);
            Logger.info(`✓ ${label}`);
        } catch (err) {
            failures++;
            Logger.error(`✗ ${label}: ${err.message || err}`);
        }
    }

    try {
        await uti_fs.WriteFile(`${config.outputDir}/README.md`, buildReadme(config), true);
    } catch (err) {
        failures++;
        Logger.error(`✗ write README snippet: ${err.message || err}`);
    }

    // Any card that failed means stale/missing output: fail the run.
    if (failures > 0) {
        Logger.setFailed(`${failures} step(s) failed; see logs above.`);
        process.exit(1);
    }

    if (config.isAction) {
        try {
            await uti_cli.CommandANDPush(config.outputDir);
        } catch (err) {
            Logger.setFailed(`git push failed: ${err.message || err}`);
            process.exit(1);
        }
    } else {
        Logger.info(`Done. Output written to ./${config.outputDir}/ (git push skipped locally).`);
    }
}

main().catch((err) => {
    Logger.setFailed(`Unexpected error: ${err.stack || err}`);
    process.exit(1);
});
